const ENV = {
  SENDGRID_API_KEY: process.env.SENDGRID_API_KEY,
  SENDGRID_SENDER_EMAIL: process.env.SENDGRID_SENDER_EMAIL,
  SENDGRID_CONTACT_ALERT_EMAIL_TEMPLATE_ID:
    process.env.SENDGRID_CONTACT_ALERT_EMAIL_TEMPLATE_ID,
};

export default ENV;
