import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ToastContainer } from 'react-toastify';

import Layout from '@/components/common/Layout';
import ContactModal from '@/components/common/ContactModal';

import './globals.css';
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Layout>{children}</Layout>

        <ContactModal />
        <div id='portal'></div>
        <ToastContainer position='bottom-center' autoClose={4000} />
      </body>
    </html>
  );
}
